#!/bin/bash
# Add the Jenkins package archive

set -e
set -o xtrace

yum --assumeyes install wget
wget -O /etc/yum.repos.d/jenkins.repo http://pkg.jenkins-ci.org/redhat/jenkins.repo
rpm --import http://pkg.jenkins-ci.org/redhat/jenkins-ci.org.key

