heat_template_version: 2013-05-23

description: >
  Heat WordPress template to support F20, using only Heat OpenStack-native
  resource types, and without the requirement for heat-cfntools in the image.
  Blabalbalba.
  WordPress is web software you can use to create a beautiful website or blog.
  This template installs a single-instance WordPress deployment using a local
  MySQL database to store the data.

parameters:

  key_name:
    type: string
    description : Name of a KeyPair to enable SSH access to the instance
  instance_type:
    type: string
    description: Instance type for WordPress server
    default: m1.small
    constraints:
      - allowed_values: [m1.small, m1.medium, m1.large]
        description: instance_type must be one of m1.small, m1.medium or m1.large
  image_id:
    type: string
    description: ID of the image to use for the WordPress server
    default: Fedora-x86_64-20-20131211.1-sda
    constraints:
      - allowed_values: [ Fedora-x86_64-20-20131211.1-sda ]
        description: >
          Image ID must be Fedora-x86_64-20-20131211.1-sda
  db_name:
    type: string
    description: WordPress database name
    default: wordpress
    constraints:
      - length: { min: 1, max: 64 }
        description: db_name must be between 1 and 64 characters
      - allowed_pattern: '[a-zA-Z][a-zA-Z0-9]*'
        description: >
          db_name must begin with a letter and contain only alphanumeric
          characters
  db_username:
    type: string
    description: The WordPress database admin account username
    default: admin
    hidden: true
    constraints:
      - length: { min: 1, max: 16 }
        description: db_username must be between 1 and 64 characters
      - allowed_pattern: '[a-zA-Z][a-zA-Z0-9]*'
        description: >
          db_username must begin with a letter and contain only alphanumeric
          characters
  db_password:
    type: string
    description: The WordPress database admin account password
    default: admin
    hidden: true
    constraints:
      - length: { min: 1, max: 41 }
        description: db_username must be between 1 and 64 characters
      - allowed_pattern: '[a-zA-Z0-9]*'
        description: db_password must contain only alphanumeric characters
  db_root_password:
    type: string
    description: Root password for MySQL
    default: admin
    hidden: true
    constraints:
      - length: { min: 1, max: 41 }
        description: db_username must be between 1 and 64 characters
      - allowed_pattern: '[a-zA-Z0-9]*'
        description: db_password must contain only alphanumeric characters

resources:
  fedora_dvd_mirror:
    type: OS::Cinder::VolumeAttachment
    properties:
      instance_uuid: { get_resource: fedora_mirror }
      mountpoint: /dev/vdc
      volume_id: a31f7736-8f14-4423-9221-c93c30201f0b
  fedora_mirror:
    type: OS::Nova::Server
    properties:
      image: { get_param: image_id }
      flavor: { get_param: instance_type }
      key_name: { get_param: key_name }
      user_data:
        str_replace:
          template: |
            #!/bin/bash -v

            [ -d /var/www/html ] || mkdir -p /var/www/html
            mount /dev/disk/by-label/Fedora\\x2020\\x20x86_64 /var/www/html/
            rm -f /etc/yum.repos.d/*
            echo '[DVD-Fedora20]' > /etc/yum.repos.d/dvd.repo 
            echo 'name=DVD-Fedora20 Repository' >> /etc/yum.repos.d/dvd.repo
            echo 'baseurl=file:///var/www/html' >> /etc/yum.repos.d/dvd.repo
            echo 'enabled=1' >> /etc/yum.repos.d/dvd.repo
            echo 'gpgcheck=0' >> /etc/yum.repos.d/dvd.repo
            yum -y install httpd
            firewall-cmd --add-service=http
            firewall-cmd --permanent --add-service=http

            systemctl start httpd.service
          params:
            db_rootpassword: { get_param: db_root_password }
            db_name: { get_param: db_name }
            db_user: { get_param: db_username }
            db_password: { get_param: db_password }
  mysql-server:
    type: OS::Nova::Server
    properties:
      image: { get_param: image_id }
      flavor: { get_param: instance_type }
      key_name: { get_param: key_name }
      user_data:
        str_replace:
          template: |
            #!/bin/bash -v

            [ -d /var/www/html ] || mkdir -p /var/www/html
            mount /dev/disk/by-label/Fedora\\x2020\\x20x86_64 /var/www/html/
            rm -f /etc/yum.repos.d/*
            echo '[DVD-Fedora20]' > /etc/yum.repos.d/dvd.repo 
            echo 'name=DVD-Fedora20 Repository' >> /etc/yum.repos.d/dvd.repo
            echo 'baseurl=http://fedora_mirror' >> /etc/yum.repos.d/dvd.repo
            echo 'enabled=1' >> /etc/yum.repos.d/dvd.repo
            echo 'gpgcheck=0' >> /etc/yum.repos.d/dvd.repo
            yum -y install mysql mysql-server

            systemctl enable mysqld.service
            systemctl start httpd.service

            # Setup MySQL root password and create a user
            mysqladmin -u root password db_rootpassword
            cat << EOF | mysql -u root --password=db_rootpassword
            CREATE DATABASE db_name;
            GRANT ALL PRIVILEGES ON db_name.* TO "db_user"@"localhost"
            IDENTIFIED BY "db_password";
            FLUSH PRIVILEGES;
            EXIT
            EOF

          params:
            fedora_mirror: { get_attr: [fedora_mirror, first_address] }
            db_rootpassword: { get_param: db_root_password }
            db_name: { get_param: db_name }
            db_user: { get_param: db_username }
            db_password: { get_param: db_password }
  wordpress:
    type: OS::Nova::Server
    properties:
      image: { get_param: image_id }
      flavor: { get_param: instance_type }
      key_name: { get_param: key_name }
      user_data:
        str_replace:
          template: |
            #!/bin/bash -v

            [ -d /var/www/html ] || mkdir -p /var/www/html
            mount /dev/disk/by-label/Fedora\\x2020\\x20x86_64 /var/www/html/
            rm -f /etc/yum.repos.d/*
            echo '[DVD-Fedora20]' > /etc/yum.repos.d/dvd.repo 
            echo 'name=DVD-Fedora20 Repository' >> /etc/yum.repos.d/dvd.repo
            echo 'baseurl=http://fedora_mirror' >> /etc/yum.repos.d/dvd.repo
            echo 'enabled=1' >> /etc/yum.repos.d/dvd.repo
            echo 'gpgcheck=0' >> /etc/yum.repos.d/dvd.repo
            yum -y install httpd wordpress

            systemctl enable httpd.service
            systemctl start httpd.service

            firewall-cmd --add-service=http
            firewall-cmd --permanent --add-service=http

            sed -i "/Deny from All/d" /etc/httpd/conf.d/wordpress.conf
            sed -i "s/Require local/Require all granted/" /etc/httpd/conf.d/wordpress.conf
            sed -i s/database_name_here/db_name/ /etc/wordpress/wp-config.php
            sed -i s/username_here/db_user/ /etc/wordpress/wp-config.php
            sed -i s/password_here/db_password/ /etc/wordpress/wp-config.php

            systemctl restart httpd.service

          params:
            fedora_mirror: { get_attr: [fedora_mirror, first_address] }
            db_rootpassword: { get_param: db_root_password }
            db_name: { get_param: db_name }
            db_user: { get_param: db_username }
            db_password: { get_param: db_password }
  wordpress_floating_ip:
    type: OS::Nova::FloatingIPAssociation
    properties:
      server_id: { get_resource: wordpress }
      floating_ip: '00151a73-e15c-45e8-8bb5-27ba6a987a06'

outputs:
  FedoraMirror:
    description: URL for the Fedora 20 x86_64 mirror
    value:
      str_replace:
        template: http://host/
        params:
          host: { get_attr: [fedora_mirror, first_address] }
