#!/bin/bash

set -e
set -o xtrace

source $(dirname $0)/defaults

install-packages git python-setuptools python-pip git-daemon-sysvinit
git clone https://gerrit.wikimedia.org/r/p/integration/jenkins-job-builder.git
cd jenkins-job-builder
pip install .

mkdir /etc/jenkins_jobs

cat > /etc/jenkins_jobs/jenkins_jobs.ini <<EOF
[job_builder]
ignore_cache=True
keep_descriptions=False

[jenkins]
user=
password=
url=http://localhost:8080/
EOF

cat > /etc/default/git-daemon <<EOF
GIT_DAEMON_ENABLE=true
GIT_DAEMON_USER=gitdaemon
GIT_DAEMON_DIRECTORY=/var/cache/git
GIT_DAEMON_OPTIONS=""
EOF

mkdir -p /var/cache/git/demo.git
git init --bare --shared /var/cache/git/demo.git
touch /var/cache/git/demo.git/git-daemon-export-ok
