#!/bin/bash

set -e
set -o xtrace

wget http://jenkins.mirror.isppower.de/debian/jenkins_1.568_all.deb
dpkg -i jenkins_1.568_all.deb||true
apt-get install -f -y

# jenkins installs into /var/lib/jenkins which is rather restrictive.
mv /var/lib/jenkins /mnt/
ln -s /mnt/jenkins /var/lib/jenkins
