heat_template_version: 2013-05-23

description: >
  Serverspec deployment

parameters:
  target:
    type: string
    description: Ip address of the server to test
    #TODO(yassine): add ip format constraint

  test_private_key:
    type: string
    description: private key to use when logging to the target

  volume_id_serverspec_image:
    type: string
    description: The VM root system

  volume_id_serverspec_datas:
    type: string
    description: The Serverspec volume

resources:
  serverspec_config:
    type: OS::Heat::SoftwareConfig
    properties:
      inputs:
        - name: target
      group: script
      config: { get_file: configure_serverspec.sh }

  serverspec_deployment:
    type: OS::Heat::SoftwareDeployment
    properties:
      config:
        get_resource: serverspec_config
      server:
        get_resource: serverspec_instance
      input_values:
        target: { get_param: target }
        test_private_key: { get_param: test_private_key }

  serverspec_instance:
    type: OS::Nova::Server
    properties:
      image: { get_param: volume_id_serverspec_image }
      flavor: m1.small
      user_data_format: SOFTWARE_CONFIG

  volume_serverspec_datas:
    type: OS::Cinder::Volume
    properties:
      image: { get_param: volume_id_serverspec_datas }
      size: 1

  attach_volume_serverspec_datas:
    type: OS::Cinder::VolumeAttachment
    properties:
      instance_uuid: { get_resource: serverspec_instance }
      volume_id: { get_resource: volume_serverspec_datas }

outputs:
  stdout_serverspec:
    value:
      get_attr: [serverspec_deployment, deploy_stdout]
  stderr_serverspec:
    value:
      get_attr: [serverspec_deployment, deploy_stderr]
