#!/bin/bash

set -e
set -o xtrace

yum --assumeyes install java jenkins

# jenkins installs into /var/lib/jenkins which is rather restrictive.
mv /var/lib/jenkins /mnt/
ln -s /mnt/jenkins /var/lib/jenkins
