heat_template_version: 2013-05-23

description: >
  A Jenkins server

parameters:
  app_key_name:
    type: string
    description : Name of a key pair to enable SSH access to instances.
    default: default
  flavor:
    type: string
    description: Flavor to use for the WordPress server.
    constraints:
      - custom_constraint: nova.flavor
  volume_id_jenkins_image:
    type: string
    description: The VM root system
  upstream_git:
    type: string
    description : IP address of the upstream git server
    default: ""

resources:
  jenkins_instance:
    type: OS::Nova::Server
    properties:
      image: { get_param: volume_id_jenkins_image }
      flavor: { get_param: flavor }
      key_name: { get_param: app_key_name }

